import { CreateAbility, MongoAbility } from "@casl/ability";
import { User } from "./models/user";
import { UserSubject } from "./subjects/user";
import { OrganizationSubject } from "./subjects/organization";
import { InviteSubject } from "./subjects/invite";
import { BillingSubject } from "./subjects/billing";
import { ParceiroSubject } from "./subjects/parceiro";
import { PessoaSubject } from "./subjects/pessoa";
import { ContaBancariaSubject } from "./subjects/conta-bancaria";
import { CentroCustoSubject } from "./subjects/centro-custo";
import { CategoriaFinanceiraSubject } from "./subjects/categoria-financeira";
import { LancamentoSubject } from "./subjects/lancamento";
import { PatrimonioSubject } from "./subjects/patrimonio";
import { LandingContentSubject } from "./subjects/landing-content";
import { OmnichannelSubject } from "./subjects/omnichannel";
type AppSubjects = UserSubject | OrganizationSubject | InviteSubject | ParceiroSubject | BillingSubject | ContaBancariaSubject | CentroCustoSubject | CategoriaFinanceiraSubject | PessoaSubject | LancamentoSubject | PatrimonioSubject | LandingContentSubject | OmnichannelSubject | ['manage', 'all'];
export type AppAbility = MongoAbility<AppSubjects>;
export type AppAbilityConstructor = CreateAbility<AppAbility>;
export * from './models/organization';
export * from './models/user';
export * from './models/categoria-financeira';
export * from './models/centro-custo';
export * from './models/conta-bancaria';
export * from './models/parceiro';
export * from './models/lancamento';
export * from './models/patrimonio';
export * from './models/landing-content';
export * from './models/omnichannel';
export * from './roles';
export * from './models/pessoa';
export * from './models/lancamento';
export declare function defineAbilitiesFor(user: User): AppAbility;
//# sourceMappingURL=index.d.ts.map